spring:
  application:
    name: blog-web-admin-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 9873

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9876/eureka/

feign:
  hystrix:
    enabled: true

debug: true